const express = require("express")
const cors = require("cors")
const { connectDb } = require("./db/connection")
const { GetCategory } = require("./apis/user/GetCategory")
const { GetSubCategory } = require("./apis/user/GetSubCategory")
const { GetServices } = require("./apis/user/GetServices")
const { GetServiceDetails } = require("./apis/user/GetServiceDetails")
const { SignUp } = require("./apis/common/SignUp")
const { Login } = require("./apis/common/Login")
const AuthMiddleWare = require("./auth/auth")
const { GetProfile } = require("./apis/user/GetProfile")
const { GetAdminCategory } = require("./apis/admin/GetAdminCategory")
const { GetAdminSubCategory } = require("./apis/admin/GetAdminSubCategory")
const { DeleteAdminCategories } = require("./apis/admin/DeleteAdminCategory")
const { GetSubCategoryByCategory } = require("./apis/user/GetSubCategoryByCategory")
const { ServicesByCategory } = require("./apis/user/ServicesByCategory")
const { ServicesBySubCategory } = require("./apis/user/ServicesBySubCategory")
const { ServicesByPrice } = require("./apis/user/ServicesByPrice")
const { GetFeedback } = require("./apis/user/GetFeedback")
const { AddGeneralInquery } = require("./apis/user/AddGeneralInquery")
const { categoryUpload, subcategoryUpload, serviceUpload, profileupload } = require("./multer/multer")
const { AddAdminCategory } = require("./apis/admin/AddAdminCategory")
const { AddAdminSubCategory } = require("./apis/admin/AddAdminSubCategory")
const { AddAdminServices } = require("./apis/admin/AddAdminServices")
const { AddFeedbacks } = require("./apis/user/AddFeedbacks")
const { GetBookings } = require("./apis/user/GetBookings")
const { GetInquiries } = require("./apis/user/GetInquiries")
const { GetAdminUsers } = require("./apis/admin/GetAdminUsers")
const { DeleteAdminSubCategories } = require("./apis/admin/DeleteAdminSubCategory")
const { DeleteAdminServices } = require("./apis/admin/DeleteAdminServices")
const { GetAdminBooking } = require("./apis/admin/GetAdminBookings")
const { GetAdminPayments } = require("./apis/admin/GetAdminPayments")
const { GetAdminFeedbacks } = require("./apis/admin/GetAdminFeedbacks")
const { GetAdminInquiries } = require("./apis/admin/GetAdminInquiries")
const { UpdateAdminCategory } = require("./apis/admin/UpdateAdminCategory")
const { UpdateAdminSubCategory } = require("./apis/admin/UpdateAdminSubCategory")
const { UpdateAdminService } = require("./apis/admin/UpdateAdminService")
const { BookService } = require("./apis/user/BookService")
const { GenOrder } = require("./apis/user/GenOrder")
const { ChangePassword } = require("./apis/common/ChangePassword")
const { VerifyPayment } = require("./apis/user/VerifyPayment")
const { UpdateAdminBooking } = require("./apis/admin/UpdateAdminBooking")
const { UpdateProfile } = require("./apis/user/UpdateProfile")
const { CloseAdminInquiry } = require("./apis/admin/CloseAdminInquiry")
const { GetAdminServices } = require("./apis/admin/GetAdminServices")
const { GetDashboard } = require("./apis/admin/GetDashboard")
const app = express()
require("dotenv").config()
const port = process.env.PORT

app.use(express.json())
app.use(cors())
app.use("/uploads/categories", express.static("uploads/categories"))
app.use("/uploads/subcategories", express.static("uploads/subcategories"))
app.use("/uploads/services", express.static("uploads/services"))
app.use("/uploads/profiles", express.static("uploads/profiles"))

app.get("/", (req, res) => {
    return res.status(200).send({ status: true, message: "Server started" })
})

// COMMON APIS
app.post("/api/signup", SignUp)
app.post("/api/login", Login)
app.post("/api/changepass", ChangePassword)

//PUBLIC API
app.get("/api/categories", GetCategory)
app.get("/api/subcategories", GetSubCategory)
app.get("/api/services", GetServices)
app.get("/api/services/:id", GetServiceDetails)
app.get("/api/subcategories/:category_id", GetSubCategoryByCategory)
app.get("/api/servicesbycategory/:category_id", ServicesByCategory)
app.get("/api/servicesbysubcategory/:subcategory_id", ServicesBySubCategory)
app.get("/api/servicesbyprice", ServicesByPrice)
app.get("/api/getfeedbacks", GetFeedback)

//AUTHENTICATED API FOR USER
app.get("/api/profile", AuthMiddleWare, GetProfile)
app.get("/api/getbookings/:user_id", AuthMiddleWare, GetBookings)
app.get("/api/getinquiries/:user_id", AuthMiddleWare, GetInquiries)
app.post("/api/addgeneralinquery", AuthMiddleWare, AddGeneralInquery)
app.post("/api/addfeedback", AuthMiddleWare, AddFeedbacks)
app.post("/api/bookservice", AuthMiddleWare, BookService)
app.post("/api/genorder", AuthMiddleWare, GenOrder)
app.post("/api/verifypayment", AuthMiddleWare, VerifyPayment)
app.post("/api/updateprofile", AuthMiddleWare, profileupload.single("profile_image"), UpdateProfile)

//AUTHENTICATED API FOR ADMIN
app.get("/api/admin/dashboard", AuthMiddleWare, GetDashboard)
app.get("/api/admin/categories", AuthMiddleWare, GetAdminCategory)
app.get("/api/admin/subcategories", AuthMiddleWare, GetAdminSubCategory)
app.get("/api/admin/services", AuthMiddleWare, GetAdminServices)
app.get("/api/admin/getusers", AuthMiddleWare, GetAdminUsers)
app.get("/api/admin/getbookings", AuthMiddleWare, GetAdminBooking)
app.get("/api/admin/getpayments", AuthMiddleWare, GetAdminPayments)
app.get("/api/admin/getfeedbacks", AuthMiddleWare, GetAdminFeedbacks)
app.get("/api/admin/getinquiries", AuthMiddleWare, GetAdminInquiries)
app.delete("/api/admin/deletecategory/:category_id", AuthMiddleWare, DeleteAdminCategories)
app.delete("/api/admin/deletesubcategory/:subcategory_id", AuthMiddleWare, DeleteAdminSubCategories)
app.delete("/api/admin/deleteservice/:id", AuthMiddleWare, DeleteAdminServices)
app.post("/api/admin/addcategory", AuthMiddleWare, categoryUpload.single("category_image"), AddAdminCategory)
app.post("/api/admin/addsubcategory", AuthMiddleWare, subcategoryUpload.single("subcategory_image"), AddAdminSubCategory)
app.post("/api/admin/addservices", AuthMiddleWare, serviceUpload.single("service_image"), AddAdminServices)
app.post("/api/admin/updatebooking", AuthMiddleWare, UpdateAdminBooking)
app.post("/api/admin/closeinquiry", AuthMiddleWare, CloseAdminInquiry)
app.post("/api/admin/updatecategory", AuthMiddleWare, categoryUpload.single("category_image"), UpdateAdminCategory)
app.post("/api/admin/updatesubcategory", AuthMiddleWare, subcategoryUpload.single("subcategory_image"), UpdateAdminSubCategory)
app.post("/api/admin/updateservice", AuthMiddleWare, serviceUpload.single("service_image"), UpdateAdminService)

connectDb()

app.listen(port, () => {
    console.log("Server started")
}
)